import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    default: 'Next.js App',
    template: '%s | Next.js App'
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='text-4xl bg-lime-200 font-semibold text-center py-6'>
          <p>This is header</p>
        </header>
        {children}
        <footer className='text-4xl bg-lime-200 font-semibold text-center py-6'>
          <h1>This is footer</h1>
        </footer>
      </body>
    </html>
  )
}
